/**
 * Represents a task entity used for managing and organizing user activities.
 */
export interface Task {
    /**
     * Optional unique identifier for the task,
     * which is typically auto-generated by the system.
     */
    id?: string;

    /**
     * A short and descriptive title for the task. This field is required.
     */
    title: string;

    /**
     * Additional details about the task. This field is optional.
     */
    description?: string;

    /**
     * Indicates whether the task is completed or still in progress.
     * This field is required.
     */
    completed: boolean;

    /**
     * The date and time when the task was created.
     * This field is optional and usually assigned by the system.
     */
    createdAt?: Date;
}
